In [4]:
import numpy as np
import math

In [5]:
L, d_k, d_v = 4, 8, 8
q = np.random.randn(L, d_k)
k = np.random.randn(L, d_k)
v = np.random.randn(L, d_v)

In [6]:
def softmax(x):
    return (np.exp(x).T / np.sum(np.exp(x), axis=-1)).T

def scaled_dot_product_attention(q, k, v, mask=None):
    d_k = q.shape[-1]
    scaled = np.matmul(q, k.T) / math.sqrt(d_k)
    if mask is not None:
        scaled = scaled + mask
    attention = softmax(scaled)
    out = np.matmul(attention, v)
    return out, attention

In [7]:
values, attention = scaled_dot_product_attention(q, k, v, mask=None)

In [8]:
print("V\n", v)
print("Attention\n", attention)

V
 [[-0.97166797 -0.72445974 -0.14492141 -0.36504448  0.39600001 -1.29059403
   1.55400334 -0.07725151]
 [ 0.9703225   0.20320333  0.00597748 -0.65981981  0.97693662 -0.04148718
   2.76405843 -0.58349439]
 [-0.23541647 -0.12086961 -0.52406952 -0.68212544 -0.67754271 -0.23636492
   0.67179366 -0.2122306 ]
 [ 0.8985193   0.83856752 -0.88650342 -0.84329342  1.03686493 -1.0993069
  -0.53747527  0.09869986]]
Attention
 [[0.72516476 0.14096337 0.06004716 0.07382471]
 [0.05840297 0.40937212 0.13249747 0.39972743]
 [0.38917516 0.19027227 0.289825   0.13072756]
 [0.41491756 0.2373883  0.16562815 0.18206598]]
