In [23]:
import sys
sys.path.insert(0, 'D:\\My Work\\Final Year Project\\Transformer\\')

In [37]:
from utils.MultiheadAttention import MultiheadAttention
from utils.LayerNormalization import LayerNormalization
from utils.PositionalEncoding import PositionalEncoding
import torch

In [51]:
torch.use_deterministic_algorithms(True)
torch.manual_seed(42)

### Multihead Attention Test

In [52]:
sequence_length = 4
batch_size = 1
input_dim = 512
d_model = 512
x = torch.randn((batch_size, sequence_length, input_dim))

In [56]:
multiheadAttention = MultiheadAttention(input_dim, d_model, num_heads=8)

In [57]:
out = multiheadAttention.forward(x, True)

x.size(): torch.Size([1, 4, 512])
qkv.size(): torch.Size([1, 4, 1536])
q.size(): torch.Size([1, 8, 4, 64]), k.size(): torch.Size([1, 8, 4, 64]), v.size(): torch.Size([1, 8, 4, 64])
values.size(): torch.Size([1, 8, 4, 64]), attention.size(): torch.Size([1, 8, 4, 4])


In [59]:
out

tensor([[[ 0.0732, -0.0193, -0.0584,  ..., -0.0308, -0.1902, -0.1485],
         [ 0.1769, -0.0508, -0.1893,  ...,  0.1780, -0.2580,  0.0156],
         [-0.2745,  0.2614, -0.1877,  ..., -0.0074,  0.2633, -0.0160],
         [ 0.1175, -0.1531,  0.0868,  ...,  0.0942,  0.1276,  0.2643]]],
       grad_fn=<ViewBackward0>)

### Layer Normalization Test

In [32]:
batch_size = 3
sentence_length = 5
embedding_dim = 8
inputs = torch.randn(sentence_length, batch_size, embedding_dim)

In [33]:
layer_norm = LayerNormalization(inputs.size()[-2:])
out = layer_norm.forward(inputs)

Mean 
 (torch.Size([5, 1, 1])): 
 tensor([[[ 0.1454]],

        [[-0.1117]],

        [[ 0.0391]],

        [[-0.0561]],

        [[ 0.1869]]])
Standard Deviation 
 (torch.Size([5, 1, 1])): 
 tensor([[[1.1102]],

        [[1.0167]],

        [[0.7659]],

        [[0.9152]],

        [[0.9104]]])
y 
 (torch.Size([5, 3, 8])) = 
 tensor([[[-1.3094,  0.6403,  0.6544,  0.2786,  0.2253, -0.3061,  1.2922,
           0.0592],
         [ 0.9788,  0.7770, -0.2407, -0.8913, -1.1516, -1.4688,  0.9593,
          -0.6275],
         [ 1.4452,  0.1703, -1.7393, -1.3726, -1.1808,  0.2415,  0.7497,
           1.8163]],

        [[ 0.3598,  1.2476,  0.3248, -0.5003,  0.3801, -0.6293, -0.3825,
          -0.0665],
         [-2.3587,  0.4149, -0.2438, -1.7483,  1.0192,  0.3914, -0.7182,
           0.2782],
         [-1.2427,  0.0298,  1.1877,  0.5554,  2.4782, -1.0471, -0.0780,
           0.3484]],

        [[-1.0112,  0.0318,  0.3384, -0.6993,  0.2628, -2.1790, -0.5686,
          -0.0576],
         [ 2.199

In [34]:
out

tensor([[[-1.3094,  0.6403,  0.6544,  0.2786,  0.2253, -0.3061,  1.2922,
           0.0592],
         [ 0.9788,  0.7770, -0.2407, -0.8913, -1.1516, -1.4688,  0.9593,
          -0.6275],
         [ 1.4452,  0.1703, -1.7393, -1.3726, -1.1808,  0.2415,  0.7497,
           1.8163]],

        [[ 0.3598,  1.2476,  0.3248, -0.5003,  0.3801, -0.6293, -0.3825,
          -0.0665],
         [-2.3587,  0.4149, -0.2438, -1.7483,  1.0192,  0.3914, -0.7182,
           0.2782],
         [-1.2427,  0.0298,  1.1877,  0.5554,  2.4782, -1.0471, -0.0780,
           0.3484]],

        [[-1.0112,  0.0318,  0.3384, -0.6993,  0.2628, -2.1790, -0.5686,
          -0.0576],
         [ 2.1997, -0.8884,  0.5221,  0.2531,  0.8266,  0.0966, -0.0336,
           1.8480],
         [-0.4816,  1.3257, -1.0303, -0.4742, -1.6855, -0.0240,  0.8093,
           0.6192]],

        [[-0.4199, -0.0336, -0.5720,  1.7175, -0.6847,  0.8181, -0.9990,
           0.0962],
         [-1.4731, -0.2536, -0.7651, -2.0695,  0.4371,  0.5696, 

### Positional Encoding Test

In [38]:
pe = PositionalEncoding(d_model=6, max_sequence_length=10)
pe.forward()

tensor([[ 0.0000,  1.0000,  0.0000,  1.0000,  0.0000,  1.0000],
        [ 0.8415,  0.5403,  0.0464,  0.9989,  0.0022,  1.0000],
        [ 0.9093, -0.4161,  0.0927,  0.9957,  0.0043,  1.0000],
        [ 0.1411, -0.9900,  0.1388,  0.9903,  0.0065,  1.0000],
        [-0.7568, -0.6536,  0.1846,  0.9828,  0.0086,  1.0000],
        [-0.9589,  0.2837,  0.2300,  0.9732,  0.0108,  0.9999],
        [-0.2794,  0.9602,  0.2749,  0.9615,  0.0129,  0.9999],
        [ 0.6570,  0.7539,  0.3192,  0.9477,  0.0151,  0.9999],
        [ 0.9894, -0.1455,  0.3629,  0.9318,  0.0172,  0.9999],
        [ 0.4121, -0.9111,  0.4057,  0.9140,  0.0194,  0.9998]])