In [1]:
import sys
sys.path.insert(0, 'D:\\My Work\\Final Year Project\\Transformer\\')

In [2]:
from utils.MultiheadAttention import MultiheadAttention
from utils.LayerNormalization import LayerNormalization
from utils.PositionalEncoding import PositionalEncoding
import torch

C:\Users\Faizan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [51]:
torch.use_deterministic_algorithms(True)
torch.manual_seed(42)

### Multihead Attention Test

In [52]:
sequence_length = 4
batch_size = 1
input_dim = 512
d_model = 512
x = torch.randn((batch_size, sequence_length, input_dim))

In [56]:
multiheadAttention = MultiheadAttention(input_dim, d_model, num_heads=8)

In [57]:
out = multiheadAttention.forward(x, True)

x.size(): torch.Size([1, 4, 512])
qkv.size(): torch.Size([1, 4, 1536])
q.size(): torch.Size([1, 8, 4, 64]), k.size(): torch.Size([1, 8, 4, 64]), v.size(): torch.Size([1, 8, 4, 64])
values.size(): torch.Size([1, 8, 4, 64]), attention.size(): torch.Size([1, 8, 4, 4])


In [59]:
out

tensor([[[ 0.0732, -0.0193, -0.0584,  ..., -0.0308, -0.1902, -0.1485],
         [ 0.1769, -0.0508, -0.1893,  ...,  0.1780, -0.2580,  0.0156],
         [-0.2745,  0.2614, -0.1877,  ..., -0.0074,  0.2633, -0.0160],
         [ 0.1175, -0.1531,  0.0868,  ...,  0.0942,  0.1276,  0.2643]]],
       grad_fn=<ViewBackward0>)

### Layer Normalization Test

In [32]:
batch_size = 3
sentence_length = 5
embedding_dim = 8
inputs = torch.randn(sentence_length, batch_size, embedding_dim)

In [33]:
layer_norm = LayerNormalization(inputs.size()[-2:])
out = layer_norm.forward(inputs)

Mean 
 (torch.Size([5, 1, 1])): 
 tensor([[[ 0.1454]],

        [[-0.1117]],

        [[ 0.0391]],

        [[-0.0561]],

        [[ 0.1869]]])
Standard Deviation 
 (torch.Size([5, 1, 1])): 
 tensor([[[1.1102]],

        [[1.0167]],

        [[0.7659]],

        [[0.9152]],

        [[0.9104]]])
y 
 (torch.Size([5, 3, 8])) = 
 tensor([[[-1.3094,  0.6403,  0.6544,  0.2786,  0.2253, -0.3061,  1.2922,
           0.0592],
         [ 0.9788,  0.7770, -0.2407, -0.8913, -1.1516, -1.4688,  0.9593,
          -0.6275],
         [ 1.4452,  0.1703, -1.7393, -1.3726, -1.1808,  0.2415,  0.7497,
           1.8163]],

        [[ 0.3598,  1.2476,  0.3248, -0.5003,  0.3801, -0.6293, -0.3825,
          -0.0665],
         [-2.3587,  0.4149, -0.2438, -1.7483,  1.0192,  0.3914, -0.7182,
           0.2782],
         [-1.2427,  0.0298,  1.1877,  0.5554,  2.4782, -1.0471, -0.0780,
           0.3484]],

        [[-1.0112,  0.0318,  0.3384, -0.6993,  0.2628, -2.1790, -0.5686,
          -0.0576],
         [ 2.199

In [34]:
out

tensor([[[-1.3094,  0.6403,  0.6544,  0.2786,  0.2253, -0.3061,  1.2922,
           0.0592],
         [ 0.9788,  0.7770, -0.2407, -0.8913, -1.1516, -1.4688,  0.9593,
          -0.6275],
         [ 1.4452,  0.1703, -1.7393, -1.3726, -1.1808,  0.2415,  0.7497,
           1.8163]],

        [[ 0.3598,  1.2476,  0.3248, -0.5003,  0.3801, -0.6293, -0.3825,
          -0.0665],
         [-2.3587,  0.4149, -0.2438, -1.7483,  1.0192,  0.3914, -0.7182,
           0.2782],
         [-1.2427,  0.0298,  1.1877,  0.5554,  2.4782, -1.0471, -0.0780,
           0.3484]],

        [[-1.0112,  0.0318,  0.3384, -0.6993,  0.2628, -2.1790, -0.5686,
          -0.0576],
         [ 2.1997, -0.8884,  0.5221,  0.2531,  0.8266,  0.0966, -0.0336,
           1.8480],
         [-0.4816,  1.3257, -1.0303, -0.4742, -1.6855, -0.0240,  0.8093,
           0.6192]],

        [[-0.4199, -0.0336, -0.5720,  1.7175, -0.6847,  0.8181, -0.9990,
           0.0962],
         [-1.4731, -0.2536, -0.7651, -2.0695,  0.4371,  0.5696, 

### Positional Encoding Test

In [38]:
pe = PositionalEncoding(d_model=6, max_sequence_length=10)
pe.forward()

tensor([[ 0.0000,  1.0000,  0.0000,  1.0000,  0.0000,  1.0000],
        [ 0.8415,  0.5403,  0.0464,  0.9989,  0.0022,  1.0000],
        [ 0.9093, -0.4161,  0.0927,  0.9957,  0.0043,  1.0000],
        [ 0.1411, -0.9900,  0.1388,  0.9903,  0.0065,  1.0000],
        [-0.7568, -0.6536,  0.1846,  0.9828,  0.0086,  1.0000],
        [-0.9589,  0.2837,  0.2300,  0.9732,  0.0108,  0.9999],
        [-0.2794,  0.9602,  0.2749,  0.9615,  0.0129,  0.9999],
        [ 0.6570,  0.7539,  0.3192,  0.9477,  0.0151,  0.9999],
        [ 0.9894, -0.1455,  0.3629,  0.9318,  0.0172,  0.9999],
        [ 0.4121, -0.9111,  0.4057,  0.9140,  0.0194,  0.9998]])

### Encoder Test

In [3]:
from utils.Encoder import Encoder

In [4]:
d_model = 512
num_heads = 8
drop_prob = 0.1
batch_size = 30
max_sequence_length = 200
ffn_hidden = 2048
num_layers = 5

encoder = Encoder(d_model=d_model, ffn_hidden=ffn_hidden, num_heads=num_heads, drop_prob=drop_prob, num_layers=num_layers)

In [5]:
x = torch.randn((batch_size, max_sequence_length, d_model)) # includes position encoding
out = encoder(x)

In [8]:
out

tensor([[[ 2.9138e-01,  2.8432e-01,  1.0141e-01,  ..., -1.9829e+00,
           3.0098e-01,  3.7182e-01],
         [ 1.4641e+00,  1.9269e+00,  9.5233e-01,  ..., -8.4063e-03,
          -6.3224e-01, -1.6609e+00],
         [ 1.3635e+00,  1.2100e+00,  9.7363e-01,  ...,  1.6020e-01,
           3.1568e-01, -3.6159e-01],
         ...,
         [ 3.1452e-01, -1.4916e+00,  6.8192e-01,  ..., -1.2381e+00,
           2.0138e-01, -3.4394e-01],
         [-1.6505e+00, -5.6938e-01,  1.4555e-01,  ..., -1.5500e+00,
           1.1242e+00, -1.1040e+00],
         [-5.8650e-01,  2.2686e-01, -3.7004e-01,  ..., -1.1355e+00,
           2.6502e-01, -9.9659e-01]],

        [[ 7.5673e-01,  3.0784e-01,  1.1882e+00,  ..., -1.0362e+00,
          -2.6960e-01, -6.2281e-01],
         [ 6.5190e-01,  7.9027e-01, -1.6014e+00,  ..., -1.1900e-01,
           1.7864e-02, -5.2839e-01],
         [ 8.2008e-01,  1.3034e-01,  9.9417e-01,  ...,  4.7898e-01,
          -1.2248e+00, -1.6766e+00],
         ...,
         [ 2.0691e-01,  1