In [1]:
import torch
from torch import nn

In [6]:
inputs = torch.Tensor([[[0.2, 0.1, 0.3], [0.5, 0.1, 0.1]]])
B, S, E = inputs.shape
inputs = inputs.reshape(S, B, E)
inputs

tensor([[[0.2000, 0.1000, 0.3000]],

        [[0.5000, 0.1000, 0.1000]]])

In [8]:
parameter_shape = inputs.size()[-2:]
gamma = nn.Parameter(torch.ones(parameter_shape))
beta = nn.Parameter(torch.zeros(parameter_shape))

In [11]:
gamma, beta

(Parameter containing:
 tensor([[1., 1., 1.]], requires_grad=True),
 Parameter containing:
 tensor([[0., 0., 0.]], requires_grad=True))

In [13]:
dims = [-(i+1) for i in range(len(parameter_shape))]

In [14]:
dims

[-1, -2]

In [16]:
mean = inputs.mean(dim=dims, keepdim=True)
mean

tensor([[[0.2000]],

        [[0.2333]]])

In [18]:
var = ((inputs - mean) ** 2).mean(dim=dims, keepdim=True)
epsilon = 1e-5
std = (var + epsilon).sqrt()
std

tensor([[[0.0817]],

        [[0.1886]]])

In [20]:
y = (inputs - mean) / std
y

tensor([[[ 0.0000, -1.2238,  1.2238]],

        [[ 1.4140, -0.7070, -0.7070]]])

In [22]:
out = gamma * y + beta
out

tensor([[[ 0.0000, -1.2238,  1.2238]],

        [[ 1.4140, -0.7070, -0.7070]]], grad_fn=<AddBackward0>)